import type { ExperienceManifest, OutputDef, ParameterDef } from "../types";
import { updatePlayer } from "./player";
import { dispose, handleTrigger, setup, tick } from "./scene";
import { applySettings } from "./settings";
import {
  BAT_AUDIO_DEFAULTS,
  BAT_CAMERA,
  BAT_ECHO_DEFAULTS,
  BAT_EXPERIENCE_AUTHOR,
  BAT_EXPERIENCE_DESCRIPTION,
  BAT_EXPERIENCE_ID,
  BAT_EXPERIENCE_NAME,
  BAT_SCENE,
  BAT_TRIGGER_ID,
  BAT_WORLD_DEFAULTS,
} from "./config";

const parameters: ParameterDef[] = [
  {
    id: "cruiseSpeed",
    label: "Cruise Speed",
    group: "Flight",
    min: 4,
    max: 24,
    default: 11,
    step: 0.5,
    unit: "m/s",
    icon: "Gauge",
  },
  {
    id: "boostSpeed",
    label: "Boost Speed",
    group: "Flight",
    min: 6,
    max: 34,
    default: 18,
    step: 0.5,
    unit: "m/s",
    icon: "Wind",
  },
  {
    id: "strafeSpeed",
    label: "Bank Drift",
    group: "Flight",
    min: 0,
    max: 14,
    default: 5.5,
    step: 0.25,
    unit: "m/s",
    icon: "MoveHorizontal",
  },
  {
    id: "climbSpeed",
    label: "Climb Speed",
    group: "Flight",
    min: 2,
    max: 18,
    default: 8,
    step: 0.25,
    unit: "m/s",
    icon: "MoveVertical",
  },
  {
    id: "turnSpeed",
    label: "Turn Response",
    group: "Flight",
    min: 0.4,
    max: 2.4,
    default: 1.2,
    step: 0.05,
    icon: "RotateCw",
  },
  {
    id: "lookSmoothing",
    label: "Look Smoothing",
    group: "Flight",
    min: 0.04,
    max: 0.35,
    default: 0.12,
    step: 0.01,
    unit: "s",
    icon: "Spline",
  },
  {
    id: "minAltitude",
    label: "Ground Clearance",
    group: "Flight",
    min: 2,
    max: 18,
    default: 5,
    step: 0.5,
    unit: "m",
    icon: "ArrowUpFromLine",
  },
  {
    id: "echoRange",
    label: "Echo Range",
    group: "Echo",
    min: 36,
    max: 180,
    default: BAT_ECHO_DEFAULTS.range,
    step: 1,
    unit: "m",
    icon: "Radar",
  },
  {
    id: "echoSpeed",
    label: "Wave Speed",
    group: "Echo",
    min: 20,
    max: 90,
    default: BAT_ECHO_DEFAULTS.speed,
    step: 1,
    unit: "m/s",
    icon: "Zap",
  },
  {
    id: "echoCooldown",
    label: "Pulse Cooldown",
    group: "Echo",
    min: 0.4,
    max: 4.5,
    default: BAT_ECHO_DEFAULTS.cooldown,
    step: 0.05,
    unit: "s",
    icon: "TimerReset",
  },
  {
    id: "autoPulseInterval",
    label: "Auto Pulse",
    group: "Echo",
    min: 0,
    max: 8,
    default: BAT_ECHO_DEFAULTS.autoPulseInterval,
    step: 0.05,
    unit: "s",
    icon: "Timer",
  },
  {
    id: "revealDuration",
    label: "Ping Tail",
    group: "Echo",
    min: 0.08,
    max: 0.9,
    default: BAT_ECHO_DEFAULTS.revealDuration,
    step: 0.02,
    unit: "s",
    icon: "Sparkles",
  },
  {
    id: "revealIntensity",
    label: "Reveal Intensity",
    group: "Echo",
    min: 0.3,
    max: 2.4,
    default: BAT_ECHO_DEFAULTS.revealIntensity,
    step: 0.05,
    icon: "Sun",
  },
  {
    id: "wireThickness",
    label: "Wire Strength",
    group: "Echo",
    min: 0.5,
    max: 2.5,
    default: BAT_ECHO_DEFAULTS.wireThickness,
    step: 0.05,
    icon: "ScanLine",
  },
  {
    id: "audioPitchCurve",
    label: "Pitch Curve",
    group: "Audio",
    min: 0.8,
    max: 2.8,
    default: BAT_AUDIO_DEFAULTS.pitchCurve,
    step: 0.05,
    icon: "AudioWaveform",
  },
  {
    id: "audioDistanceVolume",
    label: "Distance Volume",
    group: "Audio",
    min: 0.4,
    max: 2,
    default: BAT_AUDIO_DEFAULTS.distanceVolume,
    step: 0.05,
    icon: "Volume2",
  },
  {
    id: "audioMaxLayers",
    label: "Max Layers",
    group: "Audio",
    min: 1,
    max: 3,
    default: BAT_AUDIO_DEFAULTS.maxLayers,
    step: 1,
    icon: "Layers2",
  },
  {
    id: "audioDensityComplexity",
    label: "Density Complexity",
    group: "Audio",
    min: 0.2,
    max: 2,
    default: BAT_AUDIO_DEFAULTS.densityComplexity,
    step: 0.05,
    icon: "SlidersHorizontal",
  },
  {
    id: "audioDecay",
    label: "Audio Decay",
    group: "Audio",
    min: 0.4,
    max: 5,
    default: BAT_AUDIO_DEFAULTS.decay,
    step: 0.05,
    unit: "s",
    icon: "TimerReset",
  },
  {
    id: "audioDroneIntensity",
    label: "Drone Intensity",
    group: "Audio",
    min: 0,
    max: 1.5,
    default: BAT_AUDIO_DEFAULTS.droneIntensity,
    step: 0.05,
    icon: "Orbit",
  },
  {
    id: "audioMaterialInfluence",
    label: "Material Influence",
    group: "Audio",
    min: 0,
    max: 1.5,
    default: BAT_AUDIO_DEFAULTS.materialInfluence,
    step: 0.05,
    icon: "TreePine",
  },
  {
    id: "audioStereoWidth",
    label: "Stereo Width",
    group: "Audio",
    min: 0,
    max: 1,
    default: BAT_AUDIO_DEFAULTS.stereoWidth,
    step: 0.05,
    icon: "MoveHorizontal",
  },
  {
    id: "audioMasterVolume",
    label: "Audio Level",
    group: "Audio",
    min: 0,
    max: 1.6,
    default: BAT_AUDIO_DEFAULTS.masterVolume,
    step: 0.025,
    icon: "Volume2",
  },
  {
    id: "biomeScale",
    label: "Biome Scale",
    group: "World",
    min: 0.0007,
    max: 0.0024,
    default: BAT_WORLD_DEFAULTS.biomeScale,
    step: 0.0001,
    icon: "Map",
  },
  {
    id: "mountainHeight",
    label: "Mountain Height",
    group: "World",
    min: 24,
    max: 120,
    default: BAT_WORLD_DEFAULTS.mountainHeight,
    step: 1,
    unit: "m",
    icon: "Mountain",
  },
  {
    id: "treeDensity",
    label: "Tree Density",
    group: "World",
    min: 6,
    max: 44,
    default: BAT_WORLD_DEFAULTS.treeDensity,
    step: 1,
    icon: "TreePine",
  },
  {
    id: "grassDensity",
    label: "Grass Density",
    group: "World",
    min: 6,
    max: 80,
    default: BAT_WORLD_DEFAULTS.grassDensity,
    step: 1,
    icon: "Wheat",
  },
  {
    id: "fogIntensity",
    label: "Mist Density",
    group: "World",
    min: 0.2,
    max: 1,
    default: BAT_WORLD_DEFAULTS.fogIntensity,
    step: 0.02,
    icon: "CloudFog",
  },
  {
    id: "baseVisibility",
    label: "Base Visibility",
    group: "World",
    min: 0,
    max: 0.035,
    default: BAT_WORLD_DEFAULTS.baseVisibility,
    step: 0.0005,
    icon: "MoonStar",
  },
];

const outputs: OutputDef[] = [
  {
    id: "score",
    label: "Caught",
    type: "number",
  },
];

export const manifest: ExperienceManifest = {
  id: BAT_EXPERIENCE_ID,
  name: BAT_EXPERIENCE_NAME,
  description: BAT_EXPERIENCE_DESCRIPTION,
  version: "0.1.0",
  author: BAT_EXPERIENCE_AUTHOR,
  parameters,
  outputs,
  interfaces: { orientation: true, speed: true, triggers: [BAT_TRIGGER_ID] },
  camera: { ...BAT_CAMERA },
  scene: {
    background: BAT_SCENE.background,
    fogNear: BAT_SCENE.fogNear,
    fogFar: BAT_SCENE.fogFar,
    fogColor: BAT_SCENE.fogColor,
    ambientIntensity: BAT_SCENE.ambientIntensity,
    sunIntensity: BAT_SCENE.sunIntensity,
    sunColor: BAT_SCENE.sunColor,
    sunPosition: BAT_SCENE.sunPosition,
  },
  spawn: { position: BAT_SCENE.spawn },
  setup,
  tick,
  applySettings,
  updatePlayer,
  handleTrigger,
  dispose,
};
